name: 'Update Angular Action'
on: # when the action should run. Can also be a CRON or in response to external events. see https://git.io/JeBz1
  schedule:
    - cron: '30 5 * * 1'

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
      - name: Updating ng dependencies # the magic happens here !
        uses: fast-facts/ng-update@v1
        with:
          base-branch: master
          repo-token: ${{ secrets.GITHUB_TOKEN }}
